# Assignment 1
## Create a Count-Min Sketch Algorithm implementation

The objective of this assignment is to create an implementation for a Count-Min Sketch Algorithm for a small data stream. For this purpose, the first step is to install and import the needed libraries, which are mmh3, numpy and pandas.

In [173]:
!pip install mmh3
import numpy as np
import pandas as pd
import mmh3

Once the libraries are imported, it is asked to the user the number of hash functions, the hash range of the sketch that it is going to be created and the number of samples generated in the data stream.

In [174]:
# An integer input is requested and stored in a variable called hash_functions
hash_functions = int(input("Enter a number for the amount of hash functions: "))

# An integer input is requested and stored in a variable called hash_range
hash_range = int(input("Enter a number for the hash range: "))

# An integer input is requested and stored in a variable called samples
samples = int(input("Enter a number for the amount of samples: "))

Enter a number for the amount of hash functions: 10
Enter a number for the hash range: 9
Enter a number for the amount of samples: 10000


The next step is to create a list with the different characters that are going to be generated, and measured its frequency. For this use case, the letters created are from A to H.

In [175]:
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
print(letters)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']


Afterwards, it is generated the data stream using the function choice from random package of numpy library, with the letters and the samples as parameters of the function.



In [176]:
data = np.random.choice(letters, samples)
print(data)

['E' 'A' 'C' ... 'A' 'G' 'A']


Following the data stream generation, it is created a sketch (a matrix) with the number of hash functions as the number of rows and the hash range as number of columns provided. This sketch is initialized with zeros.

In [177]:
sketch = np.zeros((hash_functions,hash_range))
print(sketch)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


The next step is to traverse the whole data stream for each of the hash functions. Inside every traversing of both loops, it is computed the column position that the mmh3 hash function outputs, and the position of the sketch is incremented by one. Once the loop is finished, the sketch is printed with the updated values.

In [178]:
for i in data:
  for j in range(hash_functions):
    pos = mmh3.hash(i, j) % hash_range
    sketch[j,pos] += 1

print(sketch)

[[1253. 3721.    0.    0.    0. 1253. 2474. 1299.    0.]
 [   0. 1299. 3735. 1253.    0. 2488.    0. 1225.    0.]
 [   0. 3777. 1235.    0.    0. 3739.    0. 1249.    0.]
 [   0. 1253.    0.    0.    0. 1235. 2502. 2524. 2486.]
 [   0. 1253. 1249.    0. 2468. 1253. 1253.    0. 2524.]
 [1299.    0. 1253. 1253. 2482. 1225. 2488.    0.    0.]
 [   0. 1253. 1299. 1253.    0. 2468. 1225. 1249. 1253.]
 [2486. 1253. 1249. 1253. 1299.    0. 1235.    0. 1225.]
 [2534.    0. 1253. 1253. 1233. 1249.    0. 1253. 1225.]
 [   0.    0.    0. 1253.    0. 2488. 1249. 2552. 2458.]]


In order to compute the frequency of each character, a matrix of zeros is created, along with a dictionary that stores the different frequencies for each letter.

In [0]:
locs = np.zeros((len(letters), hash_functions))
frequencies = dict()

Once again, each of the letters is traversed for each hash function, and it is computed again the column position (hash range), and it is updated the value of the sketch into the new matrix. This new matrix stores the different counts of the Count-Min Sketch algorithm. In each row, it is stored the frequency for a different character. 

Finally, to compute the frequencies for each letter, it is applied the function amin of numpy library for each of the rows in the new matrix. This function takes the minimum value of a given array (in this case a 1D array that corresponds to the rows previously mentioned).

In [0]:
for i in letters:
  for j in range(hash_functions):
    pos = mmh3.hash(i,j) % hash_range
    locs[letters.index(i),j] = sketch[j, pos]
  frequencies[i] = np.amin(locs[letters.index(i)])

The results for the use case are the following ones:

In [183]:
print(frequencies)
print("The sum of values in the dictionary is equal to the total number of generated samples: {0}".format(sum(frequencies.values())))

{'A': 1235.0, 'B': 1299.0, 'C': 1225.0, 'D': 1253.0, 'E': 1253.0, 'F': 1233.0, 'G': 1249.0, 'H': 1253.0}
The sum of values in the dictionary is equal to the total number of generated samples: 10000.0


After running several times this algorithm with different configurations, some conclussions can be extracted. The first of them is that there exists a risk of collision issues when the number of letters is higher than the actual number of hash functions. Also, it can be said that the storage complexity of the solution is better than implementing a counter, as it is reduced from O(n) complexity to O(log(n)). This means that the actual amount of storage needed is reduced significantly.